apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: player-actions
  labels:
    strimzi.io/cluster: "grumpy-kafka"
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824