apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

#namespace: cat-stage

images:
- digest: sha256:6c191bb1cfeab23992982dd704421a041f7dfd1c0bee7c53d13b7f047444b13a
  name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs:v0.6.5
- digest: sha256:0372c31f3f596d114283c70ac186c900159ebdd08f9765f9055e547c281f9205
  name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat:v0.6.7a

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-stage.apps.cat.ocp.lan/
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
