apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cat-dev

images:
- digest: sha256:672ea767fa54da08c3699f87368c27991142741dc316f1645dbfb8b2334d1b58
  name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs:latest
- digest: sha256:6463692bf91761464319fc6e712144a935952f6de9ba14c47622e8ed093e0a9d
  name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat:latest

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-dev.apps.cluster-hnx2l.hnx2l.sandbox2725.opentlc.com/
  - HELLO=World!!!
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
