apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


images:
- digest: sha256:301dec0949acd1570c15397afd9ac3315e55606cf6a6ce6b8a0fe4869f6b4c9d
  name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs:latest
- digest: sha256:158465301a30e995d5ee9c830a107ed2f0c07cfd0597897e5290023b206910ff
  name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat:latest
