apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cat-dev

images:
- digest: sha256:ded60db813b0a45271c4106ba774d70afd339597a7bc08e809e7ddc5b6b7221a
  name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs:latest
- digest: sha256:87e4f2ba89b49240195a782d9dddfc2e98b485e2adc645571690c4b9a8c703f5
  name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat:latest

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-dev.apps.work.ocp.lan/
  - HELLO=World!!!
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
